FROM confluentinc/cp-kafka-connect:latest

RUN confluent-hub install --no-prompt microsoftcorporation/kafka-connect-cosmos:latest

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
